default:
  EXCHANGE_ID: 'binanceusdm'
  INTERVAL: '1d'
  LEVERAGE: 1
  MIN_ORDER_AMOUNT: 0.002
  MODEL_KEY: 'model.keras'
  SCALERS_KEY: 'scalers.pkl'
  STOP_LOSS: 0.00         # 0.01 = 1%
  SYMBOL: 'BTC/USDT:USDT'
  THRESHOLD: 0.00         # 0.01 = 1%
  WINDOW_SIZE: 5

production:
  DOWNLOAD_DIR: '/tmp'
  MAX_RETRIES: 0
  RETRY_DELAY: 300_000    # 5 minutes

simulation:
  BUCKET_NAME: ''                     # No need to change
  DOWNLOAD_DIR: '../downloads'        # Path to model and scalers
  START_TIME: '2024-01-01T00:00:00Z'  # ISO 8601
